//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_detail
    {
        public int ID { get; set; }
        public Nullable<int> invoiceNum { get; set; }
        public Nullable<int> ID_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual invoice_Pro invoice_Pro { get; set; }
        public virtual Product_title Product_title { get; set; }
    }
}
