//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class invoice_Pro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice_Pro()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public Nullable<int> ID_cus { get; set; }
        [Required(ErrorMessage = "Address is required.")]
        public string addressDeli { get; set; }
        public Nullable<decimal> tongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
        public virtual User User { get; set; }
    }
}
