//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int IDBook { get; set; }
        [Required(ErrorMessage = "Quantity is required.")]
        public Nullable<int> quantity { get; set; }
    
        public virtual Product_title Product_title { get; set; }
    }
}
