//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profit_revenue
    {
        public int years { get; set; }
        public int months { get; set; }
        public Nullable<int> revenue { get; set; }
        public Nullable<int> profit { get; set; }
    }
}
